# Generated by Django 5.0.6 on 2024-05-23 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_magazine', models.CharField(max_length=255, verbose_name='Имя магазина')),
                ('phone_magazine', models.CharField(max_length=255, verbose_name='Телефон магазина')),
                ('pay', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Платеж')),
                ('date_create_magazine', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание магазина')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='UserIndexMagazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create_index_user', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание индекс пользователя')),
                ('magazine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.magazine', verbose_name='Магазин')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кассир индекс магазина')),
            ],
        ),
        migrations.CreateModel(
            name='Dolg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255, verbose_name='Карыз алган адам')),
                ('summa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
                ('is_history', models.BooleanField(default=False, verbose_name='Из история')),
                ('date_add_history', models.DateField(blank=True, null=True, verbose_name='Дата добавление истории')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Из удаление')),
                ('deleted_comment', models.TextField(blank=True, verbose_name='Комментарий удаление')),
                ('date_deleted', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаление')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userindexmagazine', verbose_name='Кассир')),
                ('user_deleted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_deleted', to='core.userindexmagazine', verbose_name='Кассир удаление')),
                ('user_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_history', to='core.userindexmagazine', verbose_name='Кассир доб. истории')),
            ],
        ),
    ]
