# Generated by Django 5.0.6 on 2024-05-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='date_create_magazine',
            field=models.DateTimeField(verbose_name='Дата создание магазина'),
        ),
    ]
